const BASE_SHAPES = {
  source:
    "M 100 18 C 122 24 138 40 150 60 C 168 72 178 92 176 114 C 174 138 158 154 140 166 C 124 178 104 186 84 182 C 62 178 42 164 32 144 C 20 124 18 102 26 82 C 34 60 50 38 72 26 C 82 20 92 16 100 18 Z",
  target:
    "M 100 24 L 132 36 L 164 62 L 172 98 L 160 132 L 132 156 L 100 176 L 68 156 L 40 132 L 28 98 L 36 62 L 68 36 Z",
};

const BASE_COLORS = {
  source: "#60A5FA",
  target: "#F97316",
};

const TRANSFORM_DATA = {
  source: { x: -45, y: 6, r: -28, cx: 100, cy: 100, s: 1 },
  target: { x: 38, y: -8, r: 30, cx: 100, cy: 100, s: 0.8 },
};

const getTransformString = ({ x, y, r, cx, cy, s }) =>
  `translate(${x} ${y}) rotate(${r} ${cx} ${cy}) scale(${s})`;

const COMPLEX_SVG_SOURCE = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1.9230769230769234 -21.5 333.8461538461538 473" font-family="Alibaba PuHuiTi" width="260px" height="200px" style=""><defs data-element-type="btn-icon-defs"><symbol xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 1024 1024" version="1.1" width="200" height="200" id="btn-add-icon">\n  <path d="M512 1024C229.216 1024 0 794.784 0 512S229.216 0 512 0s512 229.216 512 512-229.216 512-512 512z m0-960C264.576 64 64 264.576 64 512s200.576 448 448 448 448-200.576 448-448S759.424 64 512 64z m192 480h-160v160a32 32 0 0 1-64 0v-160h-160a32 32 0 0 1 0-64h160v-160a32 32 0 0 1 64 0v160h160a32 32 0 0 1 0 64z" fill="#339900"></path>\n</symbol><symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1025 1024" version="1.1" width="200" height="200" id="btn-remove-icon">\n  <path d="M874.971429 149.942857C776.228571 54.857143 648.228571 0 512.914286 0S245.942857 54.857143 150.857143 149.942857c-201.142857 201.142857-201.142857 522.971429 0 724.114286C245.942857 969.142857 377.6 1024 512.914286 1024s266.971429-54.857143 362.057143-149.942857c201.142857-201.142857 201.142857-522.971429 0-724.114286m-51.2 672.914286C739.657143 906.971429 629.942857 950.857143 512.914286 950.857143s-226.742857-43.885714-310.857143-128c-171.885714-171.885714-171.885714-449.828571 0-621.714286C286.171429 117.028571 395.885714 73.142857 512.914286 73.142857s226.742857 43.885714 310.857143 128c171.885714 171.885714 171.885714 449.828571 0 621.714286" fill="#E63C33"></path>\n  <path d="M772.571429 475.428571H253.257143c-21.942857 0-36.571429 14.628571-36.571429 36.571429 0 10.971429 3.657143 18.285714 10.971429 25.6s14.628571 10.971429 25.6 10.971429H768.914286c21.942857 0 36.571429-14.628571 36.571428-36.571429s-14.628571-36.571429-32.914285-36.571429" fill="#E63C33"></path>\n</symbol></defs><defs><linearGradient id="gradient-timeline-line" x1="90" y1="41" x2="90" y2="299" gradientUnits="userSpaceOnUse"><stop offset="-2.3255813953488373%" stop-color="#1783FF"></stop><stop offset="32.55813953488372%" stop-color="#00C9C9"></stop><stop offset="67.44186046511628%" stop-color="#F0884D"></stop><stop offset="102.32558139534885%" stop-color="#D580FF"></stop></linearGradient></defs><g id="infographic-container" x="0" y="0" width="320" height="430"><g x="53.5" y="0" width="213" height="90" transform="translate(53.5, 0)"><g x="49.5" y="0" transform="translate(49.5, 0)" width="114" height="34"><foreignObject overflow="visible" x="0" y="0" width="114" height="34" data-element-type="title" data-x="0" data-y="0" data-horizontal-align="CENTER" data-vertical-align="TOP"><span xmlns="http://www.w3.org/1999/xhtml" style="overflow: visible; color: rgb(38, 38, 38); font-size: 24px; line-height: 1.4; width: 100%; height: 100%; display: flex; flex-wrap: wrap; word-break: break-word; white-space: pre-wrap; text-align: center; place-content: flex-start center; align-items: flex-start;">Infographic</span></foreignObject></g><g x="0" y="42" transform="translate(0, 42)" width="213" height="48"><foreignObject overflow="visible" x="0" y="0" width="213" height="48" data-element-type="desc" data-x="0" data-y="0" data-horizontal-align="CENTER" data-vertical-align="TOP"><span xmlns="http://www.w3.org/1999/xhtml" style="overflow: visible; color: rgb(90, 90, 90); font-size: 16px; line-height: 1.4; width: 100%; height: 100%; display: flex; flex-wrap: wrap; word-break: break-word; white-space: pre-wrap; text-align: center; place-content: flex-start center; align-items: flex-start;">Generated by @antv/infographic</span></foreignObject></g></g><g x="0" y="90" transform="translate(0, 90)"><g data-element-type="shapes-group"><path d="M 90 41 L 90 299" stroke="url(#gradient-timeline-line)" stroke-width="2" width="1" height="258"></path></g></g></g></svg>`;

const COMPLEX_SVG_TARGET = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-46.07692307692307 -21.826788330078127 786.1538461538462 480.1893432617187" font-family="Alibaba PuHuiTi" width="260px" height="200px" style=""><defs data-element-type="btn-icon-defs"><symbol xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 1024 1024" version="1.1" width="200" height="200" id="btn-add-icon">\n  <path d="M512 1024C229.216 1024 0 794.784 0 512S229.216 0 512 0s512 229.216 512 512-229.216 512-512 512z m0-960C264.576 64 64 264.576 64 512s200.576 448 448 448 448-200.576 448-448S759.424 64 512 64z m192 480h-160v160a32 32 0 0 1-64 0v-160h-160a32 32 0 0 1 0-64h160v-160a32 32 0 0 1 64 0v160h160a32 32 0 0 1 0 64z" fill="#339900"></path>\n</symbol><symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1025 1024" version="1.1" width="200" height="200" id="btn-remove-icon">\n  <path d="M874.971429 149.942857C776.228571 54.857143 648.228571 0 512.914286 0S245.942857 54.857143 150.857143 149.942857c-201.142857 201.142857-201.142857 522.971429 0 724.114286C245.942857 969.142857 377.6 1024 512.914286 1024s266.971429-54.857143 362.057143-149.942857c201.142857-201.142857 201.142857-522.971429 0-724.114286m-51.2 672.914286C739.657143 906.971429 629.942857 950.857143 512.914286 950.857143s-226.742857-43.885714-310.857143-128c-171.885714-171.885714-171.885714-449.828571 0-621.714286C286.171429 117.028571 395.885714 73.142857 512.914286 73.142857s226.742857 43.885714 310.857143 128c171.885714 171.885714 171.885714 449.828571 0 621.714286" fill="#E63C33"></path>\n  <path d="M772.571429 475.428571H253.257143c-21.942857 0-36.571429 14.628571-36.571429 36.571429 0 10.971429 3.657143 18.285714 10.971429 25.6s14.628571 10.971429 25.6 10.971429H768.914286c21.942857 0 36.571429-14.628571 36.571428-36.571429s-14.628571-36.571429-32.914285-36.571429" fill="#E63C33"></path>\n</symbol></defs><g id="infographic-container" x="0" y="0" width="694" height="460"><g width="694" height="340" x="0" y="120" transform="translate(0, 120)"><g x="347" y="170" transform="translate(347, 170)"><path d="M0,-137.986A2,2,0,0,1,2.029,-139.985A140,140,0,0,1,88.427,-108.539A2,2,0,0,1,88.695,-105.703L59.122,-70.459A2,2,0,0,1,56.338,-70.185A90,90,0,0,0,1.957,-89.979A2,2,0,0,1,0,-91.978Z" fill="#1783FF" stroke="#ffffff" stroke-width="1" data-element-type="shape" width="280" height="280"></path></g></g></g></svg>`;

const COMPLEX_CASE = {
  title: "复杂 SVG 对比（Infographic）",
  sourceSvg: COMPLEX_SVG_SOURCE,
  targetSvg: COMPLEX_SVG_TARGET,
  shapes: {
    source: "M 90 41 L 90 299",
    target:
      "M0,-137.986A2,2,0,0,1,2.029,-139.985A140,140,0,0,1,88.427,-108.539A2,2,0,0,1,88.695,-105.703L59.122,-70.459A2,2,0,0,1,56.338,-70.185A90,90,0,0,0,1.957,-89.979A2,2,0,0,1,0,-91.978Z",
  },
  colors: {
    source: "#1783FF",
    target: "#F97316",
  },
  viewBox: "-160 -160 360 500",
};

export const morphRows = [
  {
    title: "基础形态对比",
    shapes: BASE_SHAPES,
    colors: BASE_COLORS,
    viewBox: "0 0 200 200",
  },
  {
    title: "带 Transform",
    shapes: BASE_SHAPES,
    colors: BASE_COLORS,
    transformMeta: {
      label: "带 Transform",
      sourceTransform: getTransformString(TRANSFORM_DATA.source),
      targetTransform: getTransformString(TRANSFORM_DATA.target),
      config: TRANSFORM_DATA,
    },
    viewBox: "0 0 200 200",
  },
  COMPLEX_CASE,
];
